### ISSUE TITLE
Typo in gost_configuration docs

### ISSUE THREAD

**Issue by thezelus** [gost/docs#1]
In [gost_configuration.md](https://github.com/gost/docs/blob/master/gost_configuration.md)

>       verbose: true (true for logging debug and up, false to log from info and up)

Should say

>       verbose: true (true for logging debug and up, false to log from warn and up)

Here's the corresponding [line](https://github.com/gost/server/blob/master/log/logger.go#L56) in logger.go

Thanks

**Comment by tebben** [comment]
Changed, I probably wrote "info" down because I was thinking if logging without verbose flag should log from info and up instead of warn.
