### ISSUE TITLE
Typo (?) in definition of Response 201 for "Post Thing with existing Location"

### ISSUE THREAD

**Issue by janniswarnat** [gost/docs#3]
Hi all,

I recently generated Java code for your GOST API via https://apimatic.docs.apiary.io/#. In line 417 of apiary.apib there seems to be a superfluous element (",366") in the definition of Response 201 for "Post Thing with existing Location":

"@iot.selfLink": "http://localhost/v1.0/Locations(1)",366

This messes up the code creation for this response.

Best regards

Jannis

**Comment by bertt** [comment]
looks like a type error yes, can you try again now?

**Comment by janniswarnat** [comment]
Thanks! I already fixed that yesterday in my local version and the code generation worked fine (at least for the classes that I use).

**Comment by bertt** [comment]
Great!
